### ISSUE TITLE
QEMU tablet pointer freezes after pkg Install xxx

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#126]
Used furybsd-install to install 0.3.0pre2 iso onto virtual disk.  Also required the ["chmod 1777 /tmp"](https://github.com/mszoek/airyx/issues/125#issue-1000411403) fix in order for the Summer Field desktop to appear.  Then took a snapshot of the virtual disk.

Next I used "pkg install git-tiny" and it also installed xf86-input-libinput.  After the next reboot, the mouse pointer is frozen in the middle of the desktop.

If I rollback to the "After Install" snapshot and try "pkg install cmake", it again also installs xf86-input-libinput with same frozen mouse symptoms after reboot.

**Comment by markshank** [comment]
I checked my HelloSystem VM and it has xf86-input-libinput installed.  No mouse pointer issues there.

**Comment by markshank** [comment]
I found a [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244079#c5) that appears to be the root of this issue.  It looks like a patch has been developed but not tested yet.

**Comment by markshank** [comment]
Workaround (fix) as follows:

1. # pkg install meson
2. # portsnap fetch
3. # portsnap extract
4. # cd /usr/ports/devel/libudev-devd
5. # make deinstall install clean
6. # reboot and verify tablet pointer function

**Comment by mszoek** [comment]
`xf86-input-libinput` should already be loaded on airyxOS as well. It is in the list of packages for the ISO build.
Glad you found a fix! I plan to build the latest `stable/12` branch changes and latest ports tree as part of the next release so will pick the `libudev-devd` fix up as part of that :)

**Comment by markshank** [comment]
> Glad you found a fix!

Me too!  I invested a considerable amount of effort reacquainting myself with Xorg and trying to workaround libinput with evdev.  When I finally changed course and embraced libinput, things went better.  Though it meant more FreeBSD education on PKG and ports.

**Comment by mszoek** [comment]
Looks like this was only patched on the `main` branch of the ports tree so my rebuild did not pick it up. We'll have to backport the patch.

**Comment by mszoek** [comment]
On my newly installed 0.3.0pre4 (test image), ‘xf86-input-libinput` is installed.
```
Zoe-Knox-Airyx% pkg info|grep libinput
libinput-1.16.4                Generic input library
libwacom-1.5                   Adds tablet support to libinput
xf86-input-libinput-0.30.0_1   X.Org libinput input driver
```
