### ISSUE TITLE
Dual-boot support

### ISSUE THREAD

**Issue by ghost** [ravynsoft/ravynos#145]
Dual-boot is gonna be crucial for further widespread and adoption of the project. The installer should be able to: 
- Detect already present partitions and prevent them from being overwritten (unless told otherwise)
- Maybe suggest to resize them to make space for Airyx (what Calamares installer does, not sure if this is possible here)
- Install a dual-boot supporting bootloader / Write Airyx into already present bootloader if possible

**Comment by mszoek** [comment]
@chris-romanov you can use this issue for the installer improvements.
