### ISSUE TITLE
0.3.0pre3 introduces auto login behavior

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#146]
This may be a feature instead of an issue.  If so, I don't know how to toggle it off and on.

Installed 0.3.0pre3 ISO onto disk.  First boot after install presented a login screen IIRC.

Subsequent boots bypass login and go directly to desktop.  Appears that it auto logged in the user from the first (and only) login screen.

**Correction:  Never see a Login screen.  First boot does auto login for installed user.**

**Comment by mszoek** [comment]
Yes, that is a feature: the login manager (slim) is configured for autologin. You can edit /etc/slim.conf if you don't like it - just comment out the "default_user" line. I will leave this open to remind me to put a config option in the System Prefs :)

**Comment by mszoek** [comment]
No longer using slim so this can be closed.
