### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by NukeWilliams** [ravynsoft/ravynos#147]
hello @airyx team so I just need some help in building airyx operating system from source

can you tell me the build tools require + steps to build it

I have a UbuntuMate system + a macOS big sur hope you will help me to go over this issue

regards 
- NukeWilliams

**Comment by NukeWilliams** [comment]
running this command

```
make iso 
```

results in this issue

```
➜  airyx git:(main) make iso
Makefile:13: *** missing separator.  Stop.
```

**Comment by mszoek** [comment]
It looks like you have GNU make there instead of FreeBSD's make. Where are you trying to build it?
