### ISSUE TITLE
Non-Issue: Config files

### ISSUE THREAD

**Issue by kjarex** [ravynsoft/ravynos#161]
One thing I really enjoy on OSX/macOS is that (almost) all config files are plists. I don't care about them being specifically **plist**s, but I enjoy them being all in the same format. It wouldn't be a deal breaker if they weren't, but it's imo very convenient (less issues with formats one uses rarely, or one could even use (gui/tui) tools to configure just almost anything).

While this is for sure not a priority yet nor for the near future, I'm already curious:
What are airyxOS' plans in that matter? 

- Will there be an attempt to keep all config files in the one common format? 
- And if so, which format would that be? (I don't mind plist, but I am really as happy with any other format)
- And how would you want to deal with the config files of very common applications like nginx or databases or whatever; would airyx try to get them configurable in the same format? And if so, by supplying modified version of those applications (which would be nice, especially if the applications would accept both formats, but it would likely take a lot of effort to achieve, and even more to maintain), or by providing some automatic conversion into the target format?

**Comment by mszoek** [comment]
Hey! Great question. While it would be amazing to have all the files in one or two formats, I don't think it's realistic to get all applications like nginx or postgres to change their formats or even to accept patches that would allow alternate config files. Maybe in the long term. I'd love to see it!

My plan for airyxOS is to fully support Apple-compatible plists in XML and binary formats (we do now - readonly for binary at the moment, RW for XML) and use those as much as possible. They're used in app bundles, preferences, etc, so it makes sense to follow that for compatibility. We also have preliminary support for JSON plists now which I plan on adding to Foundation.framework. These are used in the new launchd implementation. We'll also wrap up most config in GUI tools so the details don't matter so much to the average user, and try to be Mac-compatible in terms of CLI.

**Comment by probonopd** [comment]
> Will there be an attempt to keep all config files in the one common format?

fwiw, it looks like FreeBSD wants to go the UCL route:
https://papers.freebsd.org/2015/bsdcan/allanjude-ucl/
