### ISSUE TITLE
Electron apps (e.g. VSCode) don't have global menus

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#169]

**Comment by PreyK** [comment]
Not sure if Hello managed to get it working, looked into this but it was a while ago.
If you are still using hello's global menu there's some more references: https://github.com/helloSystem/Menu/issues/51

**Comment by mszoek** [comment]
Interesting. I haven't looked more into it yet. We're not using Menu - ours is based on plasmashell, so according to those comments it seems like it should work. Maybe it will once I finish updating to 13.0.
