### ISSUE TITLE
Support for APFS/HFS and other essentials

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#17]
Configure the kernel
Userspace tools
Can the default root fs be APFS?

**Comment by probonopd** [comment]
Also see https://github.com/helloSystem/ISO/issues/170.

**Comment by davidchisnall** [comment]
ZFS provides most of the advantages of APFS (compression, snapshots, and so on).  Writing command-line tools that wrap libzfs_core and mimic the interface of Apple's disk-management tooling would be much easier than adding a kernel driver for APFS.

That said, APFS is very well documented by Apple and I'd *love* for someone to add FreeBSD support for it and provide some tools that abstracted over it and zfs.

**Comment by mszoek** [comment]
> ZFS provides most of the advantages of APFS (compression, snapshots, and so on). Writing command-line tools that wrap libzfs_core and mimic the interface of Apple's disk-management tooling would be much easier than adding a kernel driver for APFS.

Yep, that is exactly the strategy for the native filesystem! The intent of supporting HFS+ & APFS is mostly to read/write macOS volumes like external drives or USB sticks. I had originally thought of using APFS natively but then I discovered how good ZFS is and of course that there is no kernel support for APFS yet. *sad trombone*

**Comment by mszoek** [comment]
Similar to #81 - closing.
