### ISSUE TITLE
furybsd's initgfx chooses sfcb over vesa, which locks resolution

### ISSUE THREAD

**Issue by AceSoren** [ravynsoft/ravynos#173]
Expected result: VESA is the chosen driver, and resolution can be properly set. In my case, 1366x768
Actual result: SFCB is chosen and locks the resolution to 640x480. Installer cannot render well at this resolution and crashes after the first page.

Case: On UEFI mode, initgfx chooses SFCB to drive video to the screen, but it is much less than ideal.
Temporary solution? Disable UEFI on motherboard BIOS (or outright use a BIOS only motherboard). This leaves you with BIOS and VESA as the default driver.

**Comment by AceSoren** [comment]
The GPU is a Radeon HD 7350, which is fairly old and I wouldn't blame the live instance for not seeing it.

**Comment by probonopd** [comment]
Can you confirm PCI ID `1002:68f9`, `Cedar [Radeon HD 5000/6000/7350/8350 Series]`?

I found a Hardware Probe of helloSystem 0.5.0 where initgfx detected this and loaded the `radeon` driver:

http://bsd-hardware.info/?probe=b46845b69f&log=xorg.conf.d

**Comment by mszoek** [comment]
Closing - we no longer use initgfx
