### ISSUE TITLE
Support for Flutter and Dart

### ISSUE THREAD

**Issue by fisforfaheem** [ravynsoft/ravynos#177]
please clear this

**Comment by zyrouge** [comment]
This is actually a dumb question. Flutter apps are compiled to executables. So when the OS supports MacOS apps, it should be able to run apps built using Flutter.

**Comment by khaled-muhammad** [comment]
I hope this. It will be very powerful by the way!!

**Comment by fisforfaheem** [comment]
Not dumb at all.... If the developer clears this and mention about everything that this can run than there is huge opportunity for this OS.  Most people want Android and flutter and macOs apps to run on their laptops and if this  could fix this issue and also add Wine/liunux etc apps support as well this could be huge.... and BTW, Flutter apps are compatible with linux and macOS as well...

hope the real DEV see this opportunity and give us monthly updates

**Comment by zyrouge** [comment]
> Not dumb at all.... If the developer clears this and mention about everything that this can run than there is huge opportunity for this OS. Most people want Android and flutter and macOs apps to run on their laptops and if this could fix this issue and also add Wine/liunux etc apps support as well this could be huge.... and BTW, Flutter apps are compatible with linux and macOS as well...
> 
> hope the real DEV see this opportunity and give us monthly updates

Well they already said that "MacOS apps are currently not fully supported" and that itself clears the obvious question. And why does Flutter app works on multiple platforms? Because they are compiled to the platform's corresponding executable. So stating "Flutter apps are compatible with linux and macOS as well..." is stupid enough if you don't know how apps work. Not trying to be rude but please understand the logic behind before arising questions. And Linux and MacOS are completely two different platforms and excepting them to be simultaneously supported is just asking too much and yes this depends on the developer ofcourse.

**Comment by mszoek** [comment]
Hey guys - macOS executable support is in its infancy right now. Source compatibility is a little more mature but still early too. You may be able to run the Linux builds of Flutter apps on airyxOS using the FreeBSD Linux compatibility layer; I have not tried that but it's pretty good. Not ideal, but might help for now. As zyrouge pointed out above, though, my focus is on getting to macOS compatibility. I tend to provide pretty regular updates on Discord & Twitter (which get posted on airyx.org) and try to get at least a dot release out ~monthly, but no promises there. It depends on my free time.

**Comment by fisforfaheem** [comment]
Now that's an honest reply....the guy above was really being rude...while
not being an actual DEV working as a head on the project....

Anyway! What I meant was that you should try flutter linux apps and flutter
mac os apps on this...OS and also make it a headline...It would be huge!
even XDA featured you man! we have high hopes for you...PLEASE ALSO LOOK AT
CUTEFISH OS for design items as well... and if possible, provide a web
version of this os for testing...somehow...



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/28/22,
01:05:03 AM

**Comment by mszoek** [comment]
It looks like Dart and Flutter have not been ported to FreeBSD yet. Leaving some notes for later:

Dart SDK: https://github.com/dart-lang/sdk/wiki/Building
Depot tools dependency: http://dev.chromium.org/developers/how-tos/install-depot-tools
Forked flutter repo to airyxos/flutter.

**Comment by guruprasadah** [comment]
OK people.... I'm gonna try to create an explanation that is both useful AND keeps rudeness at a minimum.

So basically, FreeBSD has a linux compatibility layer that allows you to run linux apps on it very efficiently. Flutter has been ported to linux - and airyxOS currently uses X11 so, even in this pre-beta stage - you can technically run Flutter apps using the Linux layer.

OP hasn't really read up on how OSes work. When something is a superset of something, most of the times it is possible to use the old stuff on this new one.

But your question is valid - you don't know in detail how OSes work, so this is good.
