### ISSUE TITLE
Installing stopped to now knowing LiveCD screensave password

### ISSUE THREAD

**Issue by xet7** [ravynsoft/ravynos#210]
Hi,
I'm installing airyxOS to VM.
When installing, there started screensaver. I tried various passwords, I can not unlock screensaver and continue install process.
What is screensaver password?
Please add screensaver password to install page:
https://wiki.airyx.org/wiki/Installing_airyxOS

**Comment by gonzoMD** [comment]
The correct solution would be to disable the screensaver at all while installing.

**Comment by xet7** [comment]
Could LiveCD be modified, so that it would not have screensaver enabled?

**Comment by xet7** [comment]
For my install, I can start installing again and first disable screensaver. For future, it would be nice that someone else would not have this happen anymore.

**Comment by mszoek** [comment]
Hi! Screensaver is actually supposed to be disabled, so - that's a bug. Please open an issue for tracking :)
Another workaround might be to set a password for `liveuser` in the Terminal. There is no password set, and the screen saver does not like that.

**Comment by mszoek** [comment]
Closing - we don't use KDE or its screensaver anymore.
