### ISSUE TITLE
Install airyx miss on Applications/Utilities folder

### ISSUE THREAD

**Issue by radd59** [ravynsoft/ravynos#212]
Hi,
i use Ubuntu 20.04, i downloaded last version just today and create a VM under Virtualbox Ver. 6.1.32 r149290 (Qt5.12.8).
After live boot, i wanna to install inside the vdi disk but the installer is miss on Applications/Utilities folder<; the only app on this folder Install BSD.
Thanks.

**Comment by mszoek** [comment]
Hey - can you please confirm the version that you downloaded? There should also be a Terminal.app in that folder. Do you see that one?

**Comment by radd59** [comment]
Hi,
i downloaded this version, the name of the file is, after unzipped :
Airyx_0.3.0pre3_f12_amd64.iso
And ye, i see also Terminal.app on folder Utilities.
Thanks.

Il giorno mer 2 feb 2022 alle ore 23:29 Zoë Knox ***@***.***>
ha scritto:

**Comment by mszoek** [comment]
Won't fix - focus is on the 0.4 release now.
