### ISSUE TITLE
Filer suggestions

### ISSUE THREAD

**Issue by fossandmacosfan** [ravynsoft/ravynos#217]
- I think the icon should be redesigned, currently it looks like it's made for Hackintosh
- the folder icons are too small
- folders open in new windows by default

**Comment by probonopd** [comment]
> folders open in new windows by default

It's a feature:
https://en.wikipedia.org/wiki/Spatial_file_manager

**Comment by ashifolfi** [comment]
> It's a feature:

That's fine and all but the fact that I can't turn it off is not good. I organize my stuff into folders with folders inside folders for further organization. My display gets consumed pretty quickly.
This is one of the main reasons I'm really pushing to get filer replaced as fast as possible in airyx.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yeah, airyxOS, as opposed to helloSystem upstream, will want to default to following modern macOS's default behavior here.  (Recent versions of macOS still retain the spatial behavior more prevalent in classic Mac OS if you hide the Finder Sidebar and toolbar, though, right?)

**Comment by mszoek** [comment]
I think this is a bug. We do actually have Filer configured for spatial mode = off. It does not look like it does when spatial mode is on, but still opens new windows when folder icons are clicked. This might be related to my changes for LaunchServices - not sure. Perhaps someone could trace it and see.

**Comment by probonopd** [comment]
Confirmed: https://github.com/helloSystem/Filer/issues/134

**Comment by mszoek** [comment]
> Known regression in Filer: [helloSystem/Filer#134](https://github.com/helloSystem/Filer/issues/134). Any help appreciated.

Ah, thanks for confirming! I'll dig into it if I can find some time.

**Comment by mszoek** [comment]
Closing - we no longer use this Filer app
