### ISSUE TITLE
Dark theme suggestions

### ISSUE THREAD

**Issue by ghost** [ravynsoft/ravynos#218]
- top/status bar doesn't change when the dark theme is enabled including the right side widgets
- blue color highlighting the chosen submenu should be darker, currently the contrast is too low considering the fact that the text is white
- window buttons are stock KDE ones
- mouse is the stock KDE one
- I think the dark theme color should be monochromatic to better reflect what macOS currently has

**Comment by ashifolfi** [comment]
The default KDE theme settings aren't changed at all. So the dark and light mode options will toggle the default kde themes still present.

Dark theme is present inside airyx but it's very very unfinished and not very good. most notably filer's sidebar does not change colors properly.
