### ISSUE TITLE
When booting 0.4.0pre2: com.apple.auditd.json: failed: No such file or directory

### ISSUE THREAD

**Issue by Schamschula** [ravynsoft/ravynos#242]
I just grabbed 0.4.0pre2 and copied it onto a USB stick. When booting I get the following error

`Loading job: com.apple.auditd.json: failed: No such file or directory`

**Comment by Schamschula** [comment]
Unfortunately, the workaround of setting `init_path` causes a reboot after an uptime of 13 or 14 seconds.

**Comment by mszoek** [comment]
The "failed" message should be harmless - auditd is temporarily disabled anyway because it was unstable - but you should not be seeing that, so we can leave this open.

Are you able to see what causes the reboot with the `init_path` workaround?

**Comment by Schamschula** [comment]
I just reinstalled 0.4.0pre1, and do see the same message regarding auditd. However, the boot doesn't hang at that point.

I'll have another look tomorrow. I think there was one more line of output to the console after the above error.

As far as the boot using `init_path`, the screen immediately goes blank after the `uptime` message.

**Comment by mszoek** [comment]
I downloaded the latest build, `airyxOS_0.4.0pre2_f13_5397115307294720_amd64.iso` and wrote it to the USB stick. After booting, I do see the "com.apple.auditd.json: failed" message, but the boot is not hung. Hitting `Enter` gives me a login prompt, and switching to Alt+F2 also gives me a login prompt and I was able to log in.

Setting the `init_path="/sbin/init"` will cause a reboot because `/sbin/init` doesn't exist on the ramdisk. You can do this instead and will end up in a rescue shell:

```
set init_path="/rescue/init"
boot
```

**Comment by Schamschula** [comment]
using `set init_path="/rescue/init"` got the mouse driver to load. However, I now see the following message

a timestamp followed by `- launchd 1 - - dispatching job j=0x800851000 kickstart=0`

At this point the boot process hangs. When I hit return, I get a login prompt.

I restarted w/o setting` init_path` and got the same login prompt w/o the GUI.

**Comment by mszoek** [comment]
Yep, you will see lots of launchd messages on the console - just debug output. It sounds like everything is working fine... there is no GUI in 0.4.0preX yet as it is being rewritten without X/KDE. If you can log in to the shell as `liveuser` then it is working.

**Comment by mszoek** [comment]
You can't, really. The GUI is only partially functional in 0.4.0 so far since it is being re-done from scratch.

**Comment by Schamschula** [comment]
Thanks for the heads up on that!

It partially loaded in 0.4.0pre1, i.e. w/o the dock.

Opening apps from a drop down menu would have helped. The only way I got into the Terminal was by way of running out of space on the USB stick!

**Comment by Schamschula** [comment]
I just downloaded the April 2 iso. I've gotten in using `init_path` and su'ed into root.

However, no luck starting the `WindowServer`.

`kldload radeonkms` worked but I also had to run 'service seatd start' to get rid of another warning.

Loading the WindowServer results in `Found 0 GPUs. cannot create backend`

**Comment by mszoek** [comment]
Try `dmesg|grep drm`. Do you get some output like this?

```
[drm] Initialized i915 1.6.0 20190822 for drmn1 on minor 0
name=drmn1 flags=0x0 stride=7680 bpp=32
drmn1: fb0: i915drmfb frame buffer device
```

If not, maybe try `amdgpu.ko` instead as I believe `radeonkms.ko` is for older GPUs. It's entirely possible that the ISO is missing dependencies too.

**Comment by mszoek** [comment]
Oh. Yes. We don't have a compatible driver for nvidia GPUs yet, unfortunately.

**Comment by Schamschula** [comment]
It looks like my card needs the nvidia-driver-340 for x11. However, we're using Wayland.

**Comment by Schamschula** [comment]
FYI: I'm currently running this machine with FreeBSD-CURRENT and KDE.

**Comment by mszoek** [comment]
Closing this - the message about com.apple.auditd has been fixed and need for nVidia driver is tracked elsewhere.
