### ISSUE TITLE
Boot into 0.40pre2 GUI in VMware

### ISSUE THREAD

**Issue by TylerJaacks** [ravynsoft/ravynos#244]
Is it possible to boot in the GUI using VMware on 0.42pre2.

I have ran ```kldload i915kms  # for Intel GPUs``` which runs fine but i'm sure it doesn't work cause I need to run for VMware Video Drivers. Then running ```/System/Library/CoreServices/WindowServer.app/WindowServer``` results into Failed create backend. I'm assuming this is cause there is no VMware Video drivers.

**Comment by mszoek** [comment]
You're exactly right about the error message. Unfortunately there is no driver for VMware VGA in FreeBSD 13. There is one in 14-CURRENT that we may be able to backport.

**Comment by TylerJaacks** [comment]
Where is the driver code located?

**Comment by mszoek** [comment]
> Where is the driver code located?

It's in the port called `graphics/drm-current-kmod` as `vmwgfx`.

**Comment by ayeedshaikh** [comment]
The driver code url https://github.com/freebsd/drm-kmod/tree/drm_v5.5.19_7

**Comment by mszoek** [comment]
The new WindowServer runs in Vmware.
