### ISSUE TITLE
0.30f12 Installer stuck on Executing: /usr/sbin/pw groupmod webcamd -m root

### ISSUE THREAD

**Issue by kevincrans** [ravynsoft/ravynos#245]
I use Vmware and the errors i get are:
No packages matched for pattern 'freebsd-installer',
1 packages requested for removal: 0 locked, 1 missing
I manually quit and reboot from the harddisk, but it's not ready yet

**Comment by mszoek** [comment]
Hmm, interesting. Which Vmware product, and what do you have the VM type set for? It should be "FreeBSD 12.0 64-bit". Is it UEFI or legacy boot?

**Comment by kevincrans** [comment]
It's Uefi, else it would say it wasn't signed. I have it on FreeBSD 10 or earlier so that might be it.

**Comment by mszoek** [comment]
A desktop with a top menu bar and a tree wallpaper? That's airyxOS 0.3.0. There should be a /System/Library folder with a bunch of frameworks and system services, a palm tree icon for the 'system' menu, and some other pieces. But yes, the desktop uses Xorg and parts of KDE in that version.

**Comment by mszoek** [comment]
Have removed the need for group `webcamd` from 0.4.0pre series. Closing this.
