### ISSUE TITLE
building libmach

### ISSUE THREAD

**Issue by darvari** [ravynsoft/ravynos#246]
situation: fresh FreeBSD14-install; while building target buildworld with the source-tree cloned into /usr/src/ it fails because of missing /usr/bin/mig
one needs to build it manually in /usr/src/usr.sbin/migcom/ with "TARGET=amd24 make"
this in turn fails because of missing include "mach/std_types.def"

so libmach must be built out of /usr/src/lib/libmach
this asks for 2 missing includes:
machine/endian.h (there is one in /usr/src/tools/build/cross-build/include/common/)
machine/_types.h (there is one in /usr/obj/usr/src/amd64.amd64/tmp/usr/include)

so quickfix is to add to the Makefile in /usr/src/lib/libmach:

CFLAGS+= -I/usr/src/tools/build/cross-build/include/common -I/usr/obj/usr/src/amd64.amd64/tmp/usr/include

**Comment by mszoek** [comment]
I am pretty sure this got fixed - no issues building on a plain FreeBSD 15 vm with current source tree.
