### ISSUE TITLE
Why the rebranding from "airyx" to "ravyn"?

### ISSUE THREAD

**Issue by takusuman** [ravynsoft/ravynos#264]
Hello,
I hope that I am not being inconvenient at all, but I have a small question about the rebranding.
Why did you changed from "airyx" to "ravyn"? There is any reason in specific (such as, I do not know, copyright problems --- like when SEGA changed its console name in the U.S. from "Mega Drive" to "Genesis" because there was a company called "Mega Drive" at the time) or because it looked better?

Thanks for the attention, have a good day/afternoon/night. 😃

**Comment by dino2gnt** [comment]
Hadn't had lunch yet.  She was ravynos.

**Comment by hellisabove** [comment]
There is a company somewhere in germany that trademarked the name airyx and because of this the name was changed to ravynOS

**Comment by mszoek** [comment]
What @hellisabove said! I'm going to close this since it is not really an issue. Please use the Discussions feature for questions and stuff.
