### ISSUE TITLE
v0.4.0pre4 - Artifacts

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#291]
### After login, when the black screen with the menu bar is displayed.

There is a white dot that appears in the center of the display.  It appears that it may only be one pixel in size.

### Click on Ravyn menu icon and hover mouse over "Recent Items"

A tiny rectange is displayed next to the lower right edge of the "Recent Items" box

**Comment by mszoek** [comment]
Ah yes, the White Dot. I will fix that :)

The tiny rectangle is an empty Recent Items list. Normally you would see recently opened apps and files there, but nothing is currently populating it. We should perhaps optimize that case to not display anything.
