### ISSUE TITLE
v0.4.0pre4 -Temporary Secret Terminal does not display

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#292]
I use the \<Logo\>-\<Enter\> key combination, and occasionally see a small rectangle flash on the screen.  But it doesn't persist so I can't get focus on it.

**NOTE:**  I used a USB Logitech keyboard that has a Windows key for the \<Logo\>.  The Chromebook has a key that might be \<Logo\>, but I couldn't be sure.

**Comment by mszoek** [comment]
If something is flashing up, you've probably got the right key but maybe the terminal is crashing. If you can switch to Alt+F2 for a console, you may be able to run it from there and see what's happening:

```
export XDG_RUNTIME_DIR=/tmp/runtime.$(id -u)
foot -L
```

**Comment by markshank** [comment]
I don't see anything obviously wrong, but what do I know?

![IMG_20220704_180136889 - Copy](https://user-images.githubusercontent.com/25345979/177221090-2dd70c9a-71b5-4e9a-83b4-3838a3e8b7bf.jpg)

**Comment by markshank** [comment]
Oops, I was superuser when I tried that.  Tried again as normal user and the results are significantly different.

When I Ctrl-Alt-F1, I see a grey rectangle in the middle of the screen with a % prompt in the upper left corner.

**Comment by mszoek** [comment]
Great.. now we just need to identify why it isn't starting from WindowServer...

**Comment by mszoek** [comment]
So the reason the terminal doesn't start properly is because WindowServer runs as `nobody` (should be `_windowserver` actually) and `nobody` is not allowed to log in - meaning trying to run a terminal as `nobody` fails.
