### ISSUE TITLE
ravynOS_0.4.0pre3_f14_amd64.iso is not recognized under MacOS 12.5

### ISSUE THREAD

**Issue by pk2061** [ravynsoft/ravynos#299]
I tried to run the ravynOS_0.4.0pre3_f14_amd64.iso in Parallels Desktop, VM-Ware Fusion and Virtual-Box under MacOS 12.5 Monterey.
It seems the neither of the Programs are able to access the ISO.
In the Parallels VM I get the following error: 
ERROR: cannot open /boot/lua/loader.lua

I am also not able to mount the iso-file on the desktop.

I was on the other hand able to mount the iso-file ans read its content normally inside a Windows 10 VM.

So I guess there is in issue with the combination ravynOS_0.4.0pre3_f14_amd64.iso and MacOS.
Is there anything I can do?

Thanks for the help!
Best regards,

**Comment by mszoek** [comment]
Interesting. Is your Mac an M1 or Intel machine?

I tried pre3 on my own (Intel) Monterey Mac and had some issues. The ISO will not mount on the desktop. However, I was able to create a VM, attach the ISO to the CD, and boot from it. (Vmware Fusion 12.2.4). The VM is set up as "FreeBSD 12 64-bit" with UEFI. 

0.4.0pre3 immediately panicked after booting. (It was pretty unstable.) I then tried the latest snapshot (link below) and got to the console login prompt, which is as good as it gets for Vmware - we don't have any GPU drivers for it yet.

[This](https://mirrors.nomadlogic.org/nightly/ravynOS_0.4.0pre5_f14_5174656364707840_amd64.iso)  is the most recent snapshot build, and there is a [0.4.0pre4 release](https://github.com/ravynsoft/ravynos/releases/tag/v0.4.0pre4) as well that is newer and more stable than the one you tried.

My advice is:
* download the latest snapshot
* verify the md5 sum against the one published with the ISO
* make sure you have the VM set up as x86_64 with UEFI

And let me know if that helps :)

**Comment by pk2061** [comment]
Hi, 
thanks for the help!
I am using an Intel iMac from 2017.
I tried the to create a virtual machine in VMware by dragging the iso-file into the window where you setup your vm.
That did not work, as the iso was not recognized.

But now, following your advice, I was able to boot the live iso to the console login prompt.
- I created the VM manually and set UEFI as boot method as suggested. After that it worked!

Thanks again for the help!

Best regards
Jan

**Comment by pk2061** [comment]
If someone else runs into a similar problem:
I also was able to make it work in parallels. In order to make it work you have also to enable EFI boot.

These are modified instructions from the Parallels kb:
Open your virtual machine's configuration. 
Then go to Hardware > Boot Order and expand Advanced Settings section.
Copy and paste the following system flag:
vm.bios.efi=1  

The original can be found here:
https://kb.parallels.com/en/122735
