### ISSUE TITLE
Recommendation: Use Darwin Components (NOT XNU!)

### ISSUE THREAD

**Issue by jacobrogers256** [ravynsoft/ravynos#305]
Why do you not use the old launch d, or Bonjour. You could sprinkle in some core foundation lite. Why do you not milk apple of all their source code?

**Comment by jacobrogers256** [comment]
https://github.com/apple-oss-distributions/distribution-macOS

https://github.com/apple-oss-distributions/distribution-Developer_Tools

**Comment by linz2h** [comment]
The "old launchd" and other parts like libnotify and libdispatch are coming from the NextBSD project(2015), which is a big effort to fit XNU kernel into FreeBSD. Although it would be awesome to get the XNU parts updated to the latest version, I think it would be hard job to do it right. I think what we can do it fund this project and let @mszoek have more time to get it done, or contract the some FreeBSD developers which the right skill level

**Comment by mszoek** [comment]
Hi @jacobrogers256. We do in fact use lots of Apple's open source components (and will use more as the ability to build them grows). We have launchd, libxpc and libdispatch and I am currently working on ld64 and CommonCrypto. Replacing the Cocotron CF with CF lite and updating GCD are on my todo list.
