### ISSUE TITLE
How can I start the GUI?

### ISSUE THREAD

**Issue by lovepika** [ravynsoft/ravynos#316]
hello
When I boot the system there is only the terminal UI. 
How can I start the GUI?

**Comment by dddachui** [comment]
no gui . user cli to install os

**Comment by mszoek** [comment]
If the system detected a compatible GPU, the GUI starts automatically at boot. There are no drivers for virtual machine graphics yet, or for NVIDIA GPUs. If you have an Intel HD/Iris or an AMD or Radeon chipset, it should work.

**Comment by lovepika** [comment]
> If the system detected a compatible GPU, the GUI starts automatically at boot. There are no drivers for virtual machine graphics yet, or for NVIDIA GPUs. If you have an Intel HD/Iris or an AMD or Radeon chipset, it should work.

thanks!
