### ISSUE TITLE
Won't start in virtualbox or virtmanager ravyn 0.4pre4

### ISSUE THREAD

**Issue by Neo-29** [ravynsoft/ravynos#317]
Stuck on dispatching job Kickstart in virtualbox.
![Capture d’écran du 2022-08-22 15-20-07](https://user-images.githubusercontent.com/90937180/185931479-aabae5b8-c845-4f41-9e6b-351eb96f5713.png)

**Comment by thisham** [comment]
Just click `enter` and you will get a warning for wrong login info. Then, enter `liveuser` as username and no password. It'll be switched to CLI.

You can also use `Alt-F2` to reach the login interface.

**Comment by Neo-29** [comment]
Tks for the answer.
And how do you start on a GUI interface?  ( desktop)

**Comment by Anvith00** [comment]
As of now, there is no graphics support for virtual machines, and with NVIDIA GPUs.

**Comment by mszoek** [comment]
The UI will only run on a real GPU so far - Intel HD, Intel Iris series, AMD embedded, and Radeon discrete GPUs are supported. We're working on drivers for virtual machine graphics. Note that most of those screenshots are of the old GUI (based on KDE) which has been scrapped. The current one is not so far along. (The website needs some updating.)

**Comment by Neo-29** [comment]
Oh.... A pity... So can't test anything in vm?  I'm right?
