### ISSUE TITLE
Can't see any window

### ISSUE THREAD

**Issue by jay763190097** [ravynsoft/ravynos#324]
![image](https://user-images.githubusercontent.com/16317178/186947311-9d7110cd-0732-45a6-8eef-7603bde4c5d2.png)

**Comment by mszoek** [comment]
Virtual machine?

**Comment by jay763190097** [comment]
@mszoek Yes

**Comment by Anvith00** [comment]
Currently, there is no support for virtual machine

**Comment by mszoek** [comment]
> @mszoek Yes. I'm using KVM

As Anvith00 said, there is currently no support for the virtual GPUs in VMs. The desktop will currently run on Intel Iris/HD series, AMD embedded and Radeon series GPUs. We're working on support for virtual hardware.
