### ISSUE TITLE
Dock: Display minimized windows. Unminimize if clicked.

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#345]

**Comment by vedantmistryy** [comment]
Hello  @mszoek  can u explain i detail the problem

**Comment by mszoek** [comment]
Yes! Sorry, I converted these issues from notes in my project board so they are pretty sparse! This one is a to-do item for implementing a behavior in Dock. When an open window is minimized, Dock should display an icon for it, and un-minimize/restore that window if the icon is clicked.

The code that does the actual display and badging of the minimized window icon is there today. The missing piece is to hook into WindowServer and catch minimize/restore events to drive this. You would call this on a minimize event:

https://github.com/ravynsoft/ravynos/blob/72c6d0c4c76581491dbce4e54dfe5c4f6f51a701/CoreServices/Dock/DockItem.m#L53-L55

and if a window is restored externally from Dock, it should also catch that event and remove the minmized window icon for it.

Is that enough explanation?

**Comment by vedantmistryy** [comment]
out of enthusiasm i commented on your issue, actually i'm totally newbie in this ,i can do so if you give me time and other info to do so
thank you and sorry mate

**Comment by mszoek** [comment]
Sure, go wild. I like enthusiasm :) I probably won't get to doing this myself for a while since I'm working on another area right now, so please feel free to try doing it if you want to!

**Comment by ivedantmistry** [comment]
sorry that i couldn't solve it🥲

**Comment by mszoek** [comment]
All good!! Plenty of other tasks if you feel up to taking something on :)
