### ISSUE TITLE
Boot freezes on both VMWARE player and Virtual Box

### ISSUE THREAD

**Issue by developeranirudhprabhu** [ravynsoft/ravynos#356]
Hi,
When I try to load ISO in virtual box its stuck at following point:
![image](https://user-images.githubusercontent.com/10301434/188306866-99c24035-299d-4fc8-b888-d7d044d3b4a4.png)

My Virtualbox config is 
![image](https://user-images.githubusercontent.com/10301434/188306913-5d6cbf33-0eca-4ca8-ba65-5367014dfa20.png)

Similar thing happens on VMware player as well.

Please help. Thanks in advance

**Comment by mszoek** [comment]
That looks booted. There should be a console on tty1 (Alt+F2).  Were you expecting a GUI to load? There are no video drivers for virtual GPUs yet, unfortunately, so that only runs on real hardware.

**Comment by developeranirudhprabhu** [comment]
ohh yes it asks for login in terminal after I pressed enter. Not sure what to enter here either. Can you tell me what is the exact procedure to configure this on virtualbox? This doesnt seem similar to Ubuntu or other installations I have done on virtual box

**Comment by mszoek** [comment]
The username is `liveuser` and there is no password. This is a Developer Preview image that you can examine to see how things work. There is a script in /usr/bin/install.sh that will install the system to a hard disk - See the wiki for more info on installing.

**Comment by mszoek** [comment]
Closing this as not an issue - please open a Discussions thread if you need more info or jump on the project Discord or one of its bridged services.
