### ISSUE TITLE
OS crashed during boot

### ISSUE THREAD

**Issue by ghost** [ravynsoft/ravynos#365]
Environment:
CPU: AMD 5800H
OS: Windows 11 22H2
Virtualization: VirtualBox 6.1 , WHPX enabled.
ISO: `ravynOS_0.4.0pre4_f14_amd64.iso` ,but nightly also failed.

The kernel crashed while VirtualBox was booting the operating system.
And I didn't use VMSVGA as my default virtual graphics card.

![crash](https://user-images.githubusercontent.com/18372244/191889085-47fd133b-7527-47b8-9a08-99bba359d787.png)

**Comment by dnabre** [comment]
For what it's worth, I can readily reproduce this with Virtual Box 6.1.38 on Windows 11 (22H2) on an Intel Alder Lake CPU. Exact same thing. 

From some googling, there seem to be a similar issue with FreeBSD 12.2-12.3 or there about. Can't find what the problem actually was, and by 12.4 (I think, should have taken down release numbers) , it was fixed.

**Comment by Anvith00** [comment]
Please try the latest nightly release and see if this issue persists.

Another note to make is that GUI doesn't currently work in VMs because there's no VM graphics support (it is a WIP).

**Comment by dnabre** [comment]
My bad, hadn't seen the nightly builds. Same setup, using ravynOS_0.4.0pre5_f14_4533103283666944_amd64. Same type of crash, I think it's at the place:



![VirtualBox_ravynOS_11_10_2022_09_57_10](https://user-images.githubusercontent.com/970099/195143830-4a18ea9f-3bfe-4d56-b30d-9dd1ae9c8c7d.png)
![VirtualBox_ravynOS_11_10_2022_09_56_55](https://user-images.githubusercontent.com/970099/195143839-cebd960e-0d9b-4f21-9967-957661a01926.png)

With this newer build, it lists the FreeBSD version it's based on, 14.0-CURRENT. I grabbed the latest test build of it (FreeBSD-14.0-CURRENT-amd64-20220916-c9baa974717-258027-bootonly), and it appears to crash in the same place/way.

![VirtualBox_ravynOS_11_10_2022_10_10_52](https://user-images.githubusercontent.com/970099/195146579-2c55aae6-dbbc-49f1-9390-e10fda94e456.png)
![VirtualBox_ravynOS_11_10_2022_10_09_54](https://user-images.githubusercontent.com/970099/195146587-6b04e0a5-fdaf-4f2c-ab8e-8001b2126534.png)

Doing a sanity check with my setup, Virtualbox 6.1.38 (default/hyper-v paravirtualization) on Window 11 64-bit Version	10.0.22621 Build 22621, default) I get a similar panic using current RELEASE FreeBSD (FreeBSD-13.1-RELEASE-amd64-dvd1). Checking they most recent stable release of Debian Linux (debian-11.5.0-amd64-netinst), it crashes during boot as well. 

So, while I can reproduce the error [njlyf2011](https://github.com/njlyf2011) is hitting, it looks like it's an issue VirtualBox or its setup, and nothing particular to ravynos

**Comment by mszoek** [comment]
Privileged instruction fault is an interesting error to get... How many CPUs are configured in VirtualBox? [This reddit thread](https://www.reddit.com/r/PFSENSE/comments/q1xb2i/hyperv_processor_compatibility_fatal_trap_1/) suggests you can work around it by having more than 1.

**Comment by mszoek** [comment]
Stale
