### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by TheHolyTachanka** [ravynsoft/ravynos#386]
There hasnt been any commits in mouths. should we consider this project "dead"?

**Comment by dino2gnt** [comment]
I guess two months is technically "months".  Is two months too long for a hobby project?

**Comment by TheHolyTachanka** [comment]
> I guess two months is technically "months". Is two months too long for a hobby project?

I'd really like to see this project continue as I really like the idea of a FOSS Mac clone, and I was sad to see it abandoned. Thats why i asked.Good to know its not abandoned.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The project lead stuck a notice about this up on the project's Twitter account:  

https://twitter.com/ravynsoft/status/1613566263036608518

> People have asked if the project is dead. More like in a coma :) I’ve been sidetracked by life stuff for several months and not much progress was made since Sept 2022. Hoping to resume work next month.

(This was on January 12<sup>th</sup>.)

**Comment by ashifolfi** [comment]
We're encountering some roadblocks to development. It's not abandoned. We just aren't really able to work much right now.

**Comment by lin72h** [comment]
@mszoek just pulling in new FreeBSD current code, so not yet to your question
