### ISSUE TITLE
how to build ravynOS  source to iso file?

### ISSUE THREAD

**Issue by imgoby** [ravynsoft/ravynos#404]
Could you give me some advice about how to build ravynOS  source to iso file?
I see the source,but I don't know how to have my own iso file.

**Comment by servusdei2018** [comment]
@imgoby look inside the ISO folder. You can use [`build.sh`](https://github.com/ravynsoft/ravynos/blob/main/ISO/build.sh).

**Comment by mszoek** [comment]
Also see the `.cirrus.yml` file in the root of the repository.

**Comment by imgoby** [comment]
thank you.
