### ISSUE TITLE
install.sh failing on recent nightly ISOs

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#407]
See install.log below:

[install.log](https://github.com/ravynsoft/ravynos/files/12685001/install.log)

Reference: ravynOS_0.4.0pre5_f14_5938533999837184_amd64.iso    2023-Aug-19 01:02

Last working ISO is:  ravynOS_0.4.0pre5_f14_6455268226105344_amd64.iso    2023-Jun-19 21:26

**Comment by mszoek** [comment]
Ah. The move in FreeBSD base to a newer OpenSSL has broken dependencies in the old `pkg` and `cpdup` commands. They need to be rebuilt against a current base OS.
