### ISSUE TITLE
no amd cpu/apu support

### ISSUE THREAD

**Issue by lexyclear** [ravynsoft/ravynos#408]
It does not work out of box on amd hardware.
I tried to use it on 3500U as well as in vm on it.
I would only get a black terminal screen.
where i could login.
but then nothing else worked.
the only command i could get working after that was log out and power off.
Please fix.

**Comment by mszoek** [comment]
No GUI means it didn't detect your GPU or didn't have a driver for it. Please log in at the command prompt and run `sudo pciconf -lv`, then copy the GPU info here.

What other commands did you try that were not working?

**Comment by markusbkk** [comment]
Just realized I never checked discussions and issues on here. 😸 

The problem with AMD (which is something I want to contribute a fix to) is that device detection is somewhat incomplete, especially as there are two different sets of kernel modules for AMD (i)GPUs.

On my old Lenovo Thinkpad E535 I used the following commands to boot into the WindowServer.

```
$ su
$ kldload radeonkms
$ touch /var/run/windowserver
```

@lexyclear In your case you could try this but replace `radeonkms` with `amdgpu`.
Vega should be supported, according to the [FreeBSD support matrix](https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix).

Not sure why it failed, yet. I just got my Framework 13 AMD Edition earlier this week and will be doing some ravynOS testing with it this weekend.
