### ISSUE TITLE
Ideas to make the same OS to run on the raspberry pi

### ISSUE THREAD

**Issue by BisonPorter** [ravynsoft/ravynos#409]
I got an idea for running this OS on ARM for Raspberry Pi, I call the new name of ravynOS for Raspberry Pi "DarRISC" I derived the name RISC OS and Darwin to go together to be supportive of this special ARM computer.

**Comment by lexyclear** [comment]
ARM and apply dont really work currently outside of m1 and m2 custom soc.

**Comment by Anvith00** [comment]
> I got an idea for running this OS on ARM for Raspberry Pi, I call the new name of ravynOS for Raspberry Pi "DarRISC" I derived the name RISC OS and Darwin to go together to be supportive of this special ARM computer.

@BisonPorter Bootstrapping on arm64 is still a work in progress, I think @RangerRick was undertaking the initiative to get it running on the arm64 platform.
The wiki article for [Bootstrapping arm64](https://wiki.ravynos.com/bootstrapping-arm) was made as a self-help/ reference to get back to it sooner.

**Comment by mszoek** [comment]
Thanks for the idea. The arm64 branch could have support for RPi models if someone wants to add it. No plans to use a different name though :)
