### ISSUE TITLE
ravynos 0.4.0pre4 boot failed

### ISSUE THREAD

**Issue by dsk502** [ravynsoft/ravynos#412]
I flashed ravynOS_0.4.0pre4_f14_amd64.iso to my USB drive using balenaEtcher on macOS, and when I tried to boot from USB drive on another computer, it shows:
```
CD Loader 1.2
Building the boot loader arguments
Looking up /BOOT/LOADER... File not found
Looking up /boot/loader... File not found
Boot failed
```
But in a VirtualBox virtual machine, boot is OK.

**Comment by Aivaras-s** [comment]
had same issue but it was present only on older laptop, new pc booted from usb without problem.

for old pc iso booted when I used not rufus but ventoy for booting iso file

https://www.ventoy.net/

**Comment by mszoek** [comment]
Make sure your computer is set up to boot in UEFI mode, not legacy BIOS. The output from the bootloader above shows it looking for the legacy boot blocks.
