### ISSUE TITLE
Yo!

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [ravynsoft/ravynos#418]
Hello everything is fine? I am willing to help actively develop Ravyn
So how can I join the team?
I've never used BSD, only Linux, however, I can help with system stability and compatibility.
I'm developing a container platform on Linux. I can port the technology to BSD and help with Linux compatibility
I'm also making a container manager, I can adapt it to be Ravyn's package manager.
The things I said will not divert me from my routine.
I'm willing to help, both to improve the system itself and to free people from the need for a Mac or Linux.
I think that together we will be able to change this reality, and combine everything, Linux, Mac and even BSD in just one.
What do you think? Do you accept me?

**Comment by mszoek** [comment]
Hi! What I need most are C programmers who can work on the core OS - drivers, libraries, utilities, desktop components. A good chunk is in Objective-C so knowing that is a huge asset. Knowledge of OpenGL, Wayland, and Mach IPC/RPC is also very helpful.

RavynOS doesn't use a package manager - apps will mostly be packaged as .app bundles in .dmg images, although I hope to port Homebrew at some point and make that work.

If any of this sounds interesting, you're welcome to join the [project Discord](https://discord.com/invite/8caJbAGNwY) and help work on the system.

**Comment by LUISMAGAIVER341** [comment]
Yo

**Comment by LUISMAGAIVER341** [comment]
I'm not trying to become a contributor.
I want to be part of the team

**Comment by mszoek** [comment]
Well.. you become "part of the team" by making contributions that are valuable and being a good part of the community.
