### ISSUE TITLE
Replace Nimbus Sans with Inter

### ISSUE THREAD

**Issue by inferno986return** [ravynsoft/ravynos#424]
I am excited about the progress on building a new yet familiar UI for ravynos. I am aware from a previous issue that Nimbus Sans was chosen as the default UI font: https://github.com/ravynsoft/ravynos/issues/23

Can I request the default UI font be replaced with Inter? Apple used Helvetica 10 years ago as a go-between from Lucida Grande to San Francisco. Being a neo-grotesque sans-serif which was never designed as a screen UI font, Helvetica can be unpleasant to read, particularly at small sizes (the new Helvetica Now does address this, though).

Tobias Frere Jones of Gotham fame elaborates on why Helvetica is a poor UI font: https://usabilitypost.com/2014/06/04/tobias-frere-jones-on-helvetica/

> [Helvetica] really wasn’t designed for small sizes on screens. Words like milliliter can be very difficult to decipher. If you ever had to read or write a password with 1, i, l or I, you know the problem.

Inter is more friendly to read and it also resembles Apple's San Francisco: https://rsms.me/inter/

There's also Roboto, though it's less aesthetically pleasing. 🙂

**Comment by mszoek** [comment]
The default font is now Inter from v0.5.1.
