### ISSUE TITLE
v0.5.0 - No graphics on Chromebook with MrChromebox firmware

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#431]
Boot Chromebook from USB.

After FreeBSD boot messages scroll by, it settles into repeating messages about:

... - launchd 1 - - dispatching job j=0x23b3a64ff00 kickstart=0
... - launchd 1 - - dispatching job j=0x23b3a64ff00 kickstart=1
... - launchd 1 - - dispatching job j=0x23b3a64ff00 kickstart=0
... - launchd 1 - - dispatching job j=0x23b3a64ff00 kickstart=1

No graphics are displayed.

Graphics worked on earlier versions with this Chromebook (intel video).

**Comment by dj1ch** [comment]
Same issue here on a Chromebook with MrChromebox, I was able to escape to a shell by pushing `Enter` and logging in through there. Messages keep appearing though. 

I'm not sure if this has to do with the issue that:

> Launchd jobs created from LaunchServices are not removed after exiting

**Comment by mszoek** [comment]
It has to do with the fact that `seatd` didn't make it into `WindowServer.app/Resources` :) Working on it!

**Comment by darkoverlordofdata** [comment]
I'm getting this on a non chromebook device - an old dell inspiron :)
