### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by Ygarr** [ravynsoft/ravynos#433]
qemu-system-x86_64 \
-enable-kvm                                                    \
-m 4G                                                          \
-smp 4                                                         \
-hda   disk.img                                     \
-boot d                                                        \
-cdrom ravynOS_0.5.0_f15_amd64.iso                       \
-netdev user,id=net0,net=192.168.0.0/24,dhcpstart=192.168.0.9  \
-device virtio-net-pci,netdev=net0                             \
-vga qxl                                                       \
-device AC97

But got only console

**Comment by The-Ladle** [comment]
GUI isn't supported on VMs yet I believe

**Comment by mszoek** [comment]
That's right - there are no drivers for the virtual GPU, so no GUI.

**Comment by DragonSWDev** [comment]
@mszoek I still cannot boot to GUI on Qemu in 0.5.2. As far I know since 0.5.1 GUI no longer uses Wayland and DRM but it renders directly to framebuffer so in theory it should work on virtual machine.

**Comment by DragonSWDev** [comment]
@mszoek This is what I'm trying to do and the result is black screen with white rectangle (likely cursor) in top left. 

Command line I'm using to run Qemu:
`qemu-system-x86_64 -enable-kvm -m 8G -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd -drive if=pflash,format=raw,file=OVMF_VARS.fd -cdrom ~/Downloads/ravynOS_0.5.2_f15_amd64.iso`

**Comment by mszoek** [comment]
Try adding `-M q35` to your command. I got the same results as you with the original, but it works with this added.

**Comment by mszoek** [comment]
I'll work on making it faster again once basic things are working.
