### ISSUE TITLE
Boot ISO from USB drive with GRUB

### ISSUE THREAD

**Issue by Ygarr** [ravynsoft/ravynos#435]
I have installed on USB grub with uefi(fat32) and make config:

insmod loopback
insmod iso9660
insmod ufs2
insmod zfs
insmod exfat

search --no-floppy --fs-uuid --set=root 77DB-F851
configfile /boot/grub/grub.cfg

menuentry "RavynOS" {
    set isofile="/boot/ravynOS.iso"
    loopback loop $isofile
    kfreebsd (loop)/boot/kernel/kernel
    kfreebsd_loadenv (loop)/boot/device.hints
    set kFreeBSD.vfs.root.mountfrom=cd9660:/dev/iso9660/$isofile
    set kFreeBSD.vfs.root.mountfrom.options=rw
}

My ISO placed on exfat partition
But all i see is black screen. Is there any ideas to boot if Ventoy not support *BSD systems?

**Comment by Ygarr** [comment]
This config gives only "booting a command list message":
menuentry "RavynOS" {
 
    set isofile="/boot/ravynOS.iso"
    loopback loop $isofile
    kfreebsd (loop)/boot/kernel/kernel
    kfreebsd_loadenv (loop)/boot/device.hints
    set kFreeBSD.vfs.root.mountfrom=cd9660:/dev/iso9660/$isofile
    set kFreeBSD.vfs.root.mountfrom.options=rw
}

**Comment by mszoek** [comment]
Sorry, I don't know how that grub config works. Someone on the Discord may be able to figure it out.

ravynOS will boot directly from UEFI firmware. You just need to tell your firmware to load /boot/loader.efi.
