### ISSUE TITLE
0.5.0 can't boot into the graphical environment

### ISSUE THREAD

**Issue by TheAstralSnowstorm** [ravynsoft/ravynos#437]
I have attempted to test ravynos 0.5.0 "Sneaky Snek" multiple times, but simply doesn't work.
I've tried three computers attempting to run the system on:

Acer Aspire | V5
ASUS F556U (Tested the previous version of the system on this hardware, and actually works)
ASUS B-250M-A based Cyberpower PC

However, all of them encounter the exact same issue appearing not to be isolated to one machine exclusively, and I can safely come to the conclusion that there's a software problem.

The system appears to get stuck outputting the message: **launchd 1 - - dispatching job j=0x3caf0a41f00 kickstart = 1 (and 0)**

**Comment by markshank** [comment]
https://github.com/ravynsoft/ravynos/issues/431#issuecomment-2132453732

**Comment by mszoek** [comment]
Yep. 0.5.0 is missing a couple of critical pieces. `seatd` wasn't there, which WindowServer needs to start up, and also some of the OpenGL.framework symbols were not being found. I'm still working on that part.

**Comment by mszoek** [comment]
The only update is I'm still working on it. Things have been stalled for a bit due to life. I have a little time right now so hoping to make some more progress.

**Comment by mian196** [comment]
facing same issue here, looking forward for a fix

**Comment by mszoek** [comment]
Another update: I've resolved all the missing symbols in OpenGL.framework that WindowServer needs, so it attempts to run now. Seatd is present and starts as a launch daemon. Currently working through issues finding the DRM extensions and then I think it will start.

**Comment by KamikazeVerde** [comment]
> Another update: I've resolved all the missing symbols in OpenGL.framework that WindowServer needs, so it attempts to run now. Seatd is present and starts as a launch daemon. Currently working through issues finding the DRM extensions and then I think it will start.

Just realised that the problem about seatd doesn't just happen on latest release, but also on older. So strange

**Comment by mszoek** [comment]
WindowServer will now start again in 0.5.1. However, the desktop components are not available right now - I'm still working on it.
