### ISSUE TITLE
Compilation Error: libepoll-shim Header File Not Found

### ISSUE THREAD

**Issue by chris-romanov** [ravynsoft/ravynos#441]
Description:

While trying to compile libinput as part of the WindowServer component, I encountered a fatal error related to the libepoll-shim library.

Steps to Reproduce:

	1.	Run the make command in the directory /usr/src/CoreServices/WindowServer/libinput.
	2.	The compilation process fails with the following error:

/usr/src/CoreServices/WindowServer/libinput/src/libinput.c -o libinput.o
In file included from /usr/src/CoreServices/WindowServer/libinput/src/libinput.c:33:
/usr/obj/usr/src/amd64.amd64/tmp/usr/include/libepoll-shim/sys/epoll.h:64:10: fatal error: 'epoll-shim/detail/common.h' file not found
   64 | #include <epoll-shim/detail/common.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

**Comment by mszoek** [comment]
Can you retry this without your patch on the latest source tree and let me know if it is fixed for you?
