### ISSUE TITLE
[BUILD] Error During Installation of lib/libffi on FreeBSD 15

### ISSUE THREAD

**Issue by chris-romanov** [ravynsoft/ravynos#443]
[freebsd-15-0-current-amd64-ufs-20240822] | branch: MAIN

Description:
During the [build] installation of lib/libffi, the following error occurs:

**===> lib/libffi (install)
--- install ---
cp -f /usr/obj/usr/src/amd64.amd64/gnu/usr.bin/binutils/binutils/ranlib /usr/obj/usr/src/amd64.amd64/gnu/usr.bin/binutils/binutils/ar /usr/obj/usr/src/amd64.amd64/tmp/usr/bin
cp: /usr/obj/usr/src/amd64.amd64/gnu/usr.bin/binutils/binutils/ranlib: No such file or directory
cp: /usr/obj/usr/src/amd64.amd64/gnu/usr.bin/binutils/binutils/ar: No such file or directory
*** [install] Error code 1**

**Comment by mszoek** [comment]
> Hi Zoë:) @mszoek, temp fixed for my machine: /usr/local/bin/ **ar | ranlib** in CP libffi Makefile. binutils in ravyn?
> 
> 
> 
> [freebsd-15-0-current-amd64-ufs-20240822]
> 
> [TESTING]
> 
> [CLEAN MAKE on latest FreeBSD 15 | Goooogle Cloud latest FreeBSD 15 image]

That's one way around it. We have binutils in tree but I suspect it hasn't been built at this stage. We can make it a dependency of libffi or move binutils to the bootstrap toolchain stage so it is always available.
