### ISSUE TITLE
Unable to boot in a virtual machine

### ISSUE THREAD

**Issue by Ethank1354** [ravynsoft/ravynos#446]
When attempting to boot the latest release in a virtual machine, the system fails to boot, first stopping at being unable to initialize the qemu.usb-tablet device when running under qemu/xen, does not have this error with vmware or virtualbox. However all it fails in the same way on all three hypervisors with this: 

Mounting from ufs:/dev/md0 failed with error 2; retrying for 180 more seconds
Mounting from ufs:/dev/md0 failed with error 2.
Loader variables:
    vfs.root.mountfrom=ufs:/dev/md0
    vfs.root.mountfrom.options=rw
Manual root filesysten specification:
    <fstype>:<device> [options]
        Mount <device> using filesystem <fstype>
        and vith the specified (optional) option list.
      eg. ufs:/dev/da0s1a
            zfs:zroot/ROOT/default
            cd9660:/dev/cd0 ro
              (which is equivalent to: mount -t cd9660 -o ro /dev/cd0 /)
?                       List valid disk boot devices
.                        Yield 1 second (for background tasks)
<empty line>    Abort manual input
mountroot>

From what I can tell, it seems to be failing the initialize the virtual disk created for it. But I'm not entirely sure.

**Comment by mszoek** [comment]
This is 0.5.1?

**Comment by Ethank1354** [comment]
Yes, downloaded two days ago
-------- Original message --------From: Zoë Knox ***@***.***> Date: 2024-10-17  18:10  (GMT-05:00) To: ravynsoft/ravynos ***@***.***> Cc: Ethank1354 ***@***.***>, Author ***@***.***> Subject: Re: [ravynsoft/ravynos] Unable to boot in a virtual machine (Issue #446) 
This is 0.5.1?

**Comment by mszoek** [comment]
It boots OK for me in Vmware Fusion. Please verify the SHA256 sum of your ISO to make sure the download isn't corrupted, and that you are booting in UEFI mode. 

SHA256: `93ab3f61b8ffaab1d0fd83bd609314fe9598a4b5857f388b66551021f2c13ac8  ravynOS_0.5.1_f15_amd64.iso`

![image](https://github.com/user-attachments/assets/5e48e8f4-cee5-43fc-9abe-1b9c1b3360d6)

**Comment by mszoek** [comment]
It seems OK in qemu 9.1.0 as well provided I boot with EFI. I reproduced the error trying to boot with legacy BIOS.

![image](https://github.com/user-attachments/assets/3fa8df63-b2f1-4f04-85c4-f108bd6fd09c)

**Comment by Ethank1354** [comment]
That was it, Thanks a lot. Boots no problem once uefi is enabled in all three

**Comment by mszoek** [comment]
Awesome! Closing this :)
