### ISSUE TITLE
Install and Dev ravynOS

### ISSUE THREAD

**Issue by chris-romanov** [ravynsoft/ravynos#451]
Dear Zoë @mszoek, after installing (using the old method: https://wiki.ravynos.com/installing-ravynos/installing-pygmy-marmoset) and rebooting, the system doesn’t load tty. I want to start debugging WindowServer. Please, could you provide more details on how to install ravynOS and start debugging on WindowServer? Also, how can I install GIT after the installation? pkg install perhaps? Can I use UTM (mac on M1)? I understand that writing a full guide takes a lot of time, but if possible, could you provide instructions on how to successfully install ravynOS and start debugging WindowServer? Thank you very much!

**Comment by mszoek** [comment]
If you're seeing a black screen with mouse cursor, you can hit Shift-Q to exit the WindowServer shell and get to the tty. Does that help?

**Comment by preland** [comment]
Note: if you start seeing a bunch of printed lines from launchd, or the log freezes, then WindowServer failed to….do something

**Comment by 995qa** [comment]
Use Alt + F2 to go to tty2
User is liveuser without a password
