### ISSUE TITLE
VirtualBox hanging at startup

### ISSUE THREAD

**Issue by bsilver1701** [ravynsoft/ravynos#74]
Booted from the 0.2.2 (atomic) iso, and it hung at the booting message. A boot -v flag shows it stopped after "atrtc0: providing initial system time" message.

After troubleshooting on chat, it seems that using the VirtualBox VBoxSVGA video controller allowed it to boot to the GUI; using the VMSVGA would make it hang. I also had it set to 32MB of video RAM, don't know if that affected the bootup, though.

**Comment by bsilver1701** [comment]
This was using VBox 6.1.26 r145957 Qt5.6.3, MacOS 11.5.1 host.

**Comment by carlio** [comment]
Same issue for me, with:

Host: Windows 10 Pro version 21H1
Virtualbox: Version 6.1.22 r144080 (Qt5.6.2)

Switching from VMSVGA -> VboxSVGA fixed the issue.

**Comment by Theo-codatte** [comment]
Same issue on Mojave 10.14.6 and VBOX 6.1.18

Yes, Switching from VMSVGA -> VboxSVGA fixed the issue

Awesome welcome screen'll be fired displayed then !

**Comment by mszoek** [comment]
I added a Troubleshooting section to the FAQ on airyx.org with something about this issue for now. Leaving it open until we find the root cause.

**Comment by grahamperrin** [comment]
Not an Airyx issue. 

Essentially: 

* where guest additions are installed, use VboxSVGA.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254266#c7

### Side note

I intended a single update to the package message, to cover multiple issues, however I never gained a response to this call for testing: 

* [CFT: virtualbox-ose on any RELEASE of FreeBSD: virtualbox-ose-additions: audio: input : freebsd](https://old.reddit.com/r/freebsd/comments/ntki7u/cft_virtualboxose_on_any_release_of_freebsd/)

– so I'll go ahead with a piecemeal update to the package message (re: VboxSVGA alone).

**Comment by grahamperrin** [comment]
Off-topic from hangs, management of expectations: you might find that the two services don't work as expected. See for example https://github.com/helloSystem/ISO/issues/87

**Comment by mszoek** [comment]
Thanks for the heads up!
