### ISSUE TITLE
ARM64 edition

### ISSUE THREAD

**Issue by mcandre** [ravynsoft/ravynos#76]
When can we get an ARM64 port of Airyx, for even better support of Darwin applications?

**Comment by mszoek** [comment]
That would be "far future" at the earliest. Running Darwin *binaries* is not supported (yet) on Airyx; the first two goals are to make something looking/feeling like macOS and to achieve source-level compatibility. PureDarwin or Darling would be better bets for running current Darwin apps although I don't know if either support ARM.

**Comment by talaviram** [comment]
It might be nicer to change this topic.
As it might be reasonable to support arm64 for devices such as Apple Silicon Macs but most importantly Raspberry Pi.

Darwin / frameworks support and arch is a different thing.

**Comment by mszoek** [comment]
Good point. Let's keep it as "will we support ARM" and the answer there is "eventually" :)

**Comment by mszoek** [comment]
Closing this as @RangerRick is actively working on the arm64 support. We can track specific issues against it.

**Comment by RangerRick** [comment]
Just as an update, as of the last week or two, kernel, base, and system build just fine in mainline without any patches. All that's left to get working is ISO/installer support, and then it's time to test bootability. ;)
