### ISSUE TITLE
Vagrant boxes

### ISSUE THREAD

**Issue by mcandre** [ravynsoft/ravynos#78]
Can we get Vagrant boxes published for Airyx, for super convenient use as Virtual Machines?

Examples:

* https://roboxes.org/
* https://github.com/mcandre/packer-templates

**Comment by mszoek** [comment]
Maybe? :) I need to get 0.3.0 built and solid first, then it might be a good candidate for this. You seem to have done this a few times. Would you be willing to help package it? I don't know that much about Vagrant.
