### ISSUE TITLE
Hardware support

### ISSUE THREAD

**Issue by mcandre** [ravynsoft/ravynos#79]
How well does Airyx support common hardware, at including older Intel amd64 chips, video drivers, WiFi, and Bluetooth?

**Comment by mszoek** [comment]
As well as FreeBSD 12.2 does. My general guidance is to have 4 cores and 8 GB RAM but it probably runs fine in less.
I just run it in VMware Fusion until I can get a FreeBSD-compatible laptop to use for this so that's about all I can say for now.

**Comment by grahamperrin** [comment]
> … until I can get a FreeBSD-compatible laptop …

(Do you have hardware that's not yet compatible for boot purposes?)

**Comment by mszoek** [comment]
I have two laptops now that can boot it and one runs it well. The other doesn't have drivers for its trackpad or wifi, and I don't think its MMC disk was detected either.

The working one is an old Dell Inspiron 7520 (?): Intel 4-core i7, 8GB RAM, 120GB SSD, iwn 2030 wifi, switchable Intel i915 and Radeon graphics (which I haven't played with yet). The battery doesn't work anymore but it's OK plugged in for some testing.

The not so working one is a recent Acer Spin SP111-33: Intel 4-core Pentium N5000, 4GB RAM, 64GB MMC, Intel UHD603 graphics and I'll have to check again what the wifi is. The touchpad is some kind of Philips I2C device which I haven't managed to get working with iichid yet.

**Comment by grahamperrin** [comment]
> … MMC … a recent Acer Spin SP111-33: …

I'm not familiar with the range, however https://bsd-hardware.info/?probe=dd7644026b&log=gpart appears to show an SP111-_32N_ booting from MMC with FreeBSD 12.2-RELEASE-p3.
