### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by mcandre** [ravynsoft/ravynos#80]
FreeBSD pkg is a great start. Can we get a majority of the Homebrew formulas working as well?

**Comment by mszoek** [comment]
I'm sure we can with sufficient time & effort. What would the advantage be of doing that though? Are they substantially different from what is in packages?

**Comment by probonopd** [comment]
Came across [Linuxbrew on FreeBSD](https://gist.github.com/cielavenir/a26f82b06f969ffd9113ffbae22573d3), but I am wondering the same thing: What would be its advantage?

Could it prevent us from [such issues](https://github.com/helloSystem/ISO/issues/267)?

**Comment by mszoek** [comment]
Hmm.. it might prevent such issues.

**Comment by vic3t3chn0** [comment]
I installed a fork from my brew repo, I have 0.3.0 running on a HP laptop from 2015. I could install brew from a few steps from ruby instalment. In despite of my instalment has issues like ./brew update or even ./brew install irrlicht it came with an error from MacOS string. I will fix it. I am helping the community in my spare time.

**Comment by mszoek** [comment]
As of 0.5.X, FreeBSD packages can be used again with no modifications. They install into /usr/local as usual and should not break anything in the base system. 🤞🏼 🤞🏼 If they do, remove the pkg and don't use it ;)

We can revisit Homebrew once the full Mach-O port is done and it looks more like Darwin.
