### ISSUE TITLE
Common code

### ISSUE THREAD

**Issue by kasajian** [ravynsoft/ravynos#83]
Will it be possible to create binaries that can be installed and run on both macOS and Airyx, assuming they are limited to such that they dont attempt to access APIs and services that are not available?
Will there be a way to do this for GUI apps as well, or are they only source-compatilble, requiring recompile?
And also, would there be a way test at runtime and make platform specific calls depending on where it's running.

**Comment by mszoek** [comment]
In the shorter term, it would be possible to build a "fat" bundle that contains both Airyx and macOS executables which share the Resources, Info.plist, etc. Longer term (like _really_ long!) I would like to support loading Mach-O Darwin binaries and dynamically linking them against the same frameworks. This is tricky but should be possible. Then the same executable could be run on either platform.

**Comment by kasajian** [comment]
That's a good long term goal.  But it seems that for the foreseeable future, it'd be best to simply target Airyx as a separate platform.  That's certainly not a big deal at all.

I assume you agree.

**Comment by mszoek** [comment]
Absolutely.

**Comment by kasajian** [comment]
One thing I thing would be interesting to do as this project moves forward is to make it easy for developers to create software for this platform.   For instance, I'm sure standard stuff such as NodeJS already work.
It would be interesting to target tools that target desktop environments, the ones that say their tools can target "Windows, Mac and Linux", such as Electron, Photino, WxWidgets, Qt, SWT (used by Eclipse) etc.

Today, when a developer creates software using some of these tools and frameworks, resulting software may all look the same on every platform, or attempt to take on the themes and styles of the specific platform.   So on Windows it looks like a Windows app.  On Mac it looks like a Mac app.    It would be good to have a path to not only support these frameworks but also have the software produces by these tools and frameworks take on some of the qualities of Airyx.

If the incremental cost of targeting "one more platform" is low enough, some developers may choose to support it.   With enough evangalizing we can push that further ahead.

And finally, those who have never heard of Airyx might be exposed to it when they, say, go to download "Visual Studio Code", and they are asked which platform to download it for: "Windows, Mac, Linux or Airyx"

**Comment by probonopd** [comment]
From my experience, Qt comes closest to a really usable cross-platform development environment. Not saying it is perfect, but there are many real-world applications, including commercial ones, written in it for Windows, Mac, and Linux. And it runs on platforms like FreeBSD and Haiku as well.
